### ISSUE TITLE
Create Hex.pm package

### ISSUE THREAD

**Issue by scohen** [ferd/pobox#4]
I'd like to publish https://github.com/pinterest/elixometer as a hex package, but first pobox needs to be published. 

Would it be possible to publish your latest version via hex? 

Thanks!

**Comment by ferd** [comment]
https://hex.pm/packages/pobox

There you go!

**Comment by scohen** [comment]
Thanks, @ferd. You rock. 

Seriously, I'm in love with recon. We're getting married later in the year.  You're invited.
