### ISSUE TITLE
Split out buffer implementation from pobox

### ISSUE THREAD

**Issue by edescourtis** [ferd/pobox#8]
Split out buffer implementation from pobox. 

We have a case where we need a sophisticated queueing discipline (fair queueing + priorities). We could benefit from using this library if the buffer implementation was separate from the pobox module.

**Comment by ferd** [comment]
the queue implementation is quite literally the `queue` module?

**Comment by ferd** [comment]
If you look at the code internally for the queues: https://github.com/ferd/pobox/blob/master/src/pobox.erl#L280-L306

You can see the kind of generic switching but all queue operations directly map to the stdlib's queue module.

**Comment by edescourtis** [comment]
Understood. But what I mean is that for some use cases it would be useful to have the buffer implementation be pluggable. We need a combination of fair queueing and priority-based queueing which is not what is implemented in the queue module.

**Comment by edescourtis** [comment]
Thanks!
